services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/siamese_db
      - PORT=3333
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3333/api
      - PORT=3000
      - VITE_PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: siamese_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
